<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>azsqlbcp</ToolCommandName>
    <PackageId>azsqlbcp</PackageId>
    <PackageIcon>azsqlbcp.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="azsqlbcp.Tests" />
    <Using Include="AzSqlBcp.Services.BulkCopy" />
    <Using Include="AzSqlBcp.Services.Checkpoint" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Devlead.Console" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../icon/azsqlbcp.png" Pack="true" PackagePath="\" />
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
