<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="AzSqlBcp.Services.BulkCopy" />
    <Using Include="AzSqlBcp.Services.Checkpoint" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\azsqlbcp\azsqlbcp.csproj" />
  </ItemGroup>

</Project>
